ViewModels/CallbackViewModel.cs
using CIS2Auth.Dto;

namespace CIS2Auth.ViewModels
{
    public class CallbackViewModel
    {
        public string Code { get; set; }
        public string State { get; set; }
    }
}

Pages/ApplicationAccess.cshtml.cs
using CIS2Auth.Dto;
using CIS2Auth.Jwt;
using CIS2Auth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace CIS2Auth.Pages
{
    public class ApplicationAccessModel : PageModel
    {

        private static HttpClient client = new HttpClient();

        [BindProperty]
        public string HelperText =>
            $"To generate a bearer token in App access we POST to {AuthSettings.TokenApplicationAccessUri} {GeneratePayloadJson("jwt")}";


        [BindProperty]
        public AuthSettingsViewModel AuthSettings { get; set; }

        public void OnGet()
        {
            AuthSettings = new AuthSettingsViewModel();
        }


        public string JWT => GenerateJWT();

        public string PrivateKey => AuthSettings.PRIVATE_KEY;
        public string PublicKey => AuthSettings.PUBLIC_KEY;

        public string Kid => AuthSettings.Kid;

        private string GenerateJWT()
        {
            var handler = new JwtHandler(AuthSettings.TokenApplicationAccessUri, AuthSettings.AppAccessApiKey, Kid, AuthSettings.PRIVATE_KEY);
            return handler.generateJWT(5);
        }

        public string GetTokenPayload => GeneratePayloadJson(GenerateJWT());

        private string GeneratePayloadJson(string jwt)
        {
            return JsonConvert.SerializeObject(GeneratePayload(jwt), Formatting.Indented);
        }

        private Dictionary<string, string> GeneratePayload(string jwt)
        {

            return new Dictionary<string, string>()
            {
                {"client_assertion",jwt},
                {"client_assertion_type","urn:ietf:params:oauth:client-assertion-type:jwt-bearer" },
                {"grant_type", "client_credentials"}

            };
        }



        public async Task<IActionResult> OnPost()
        {
            client.DefaultRequestHeaders.Add("cache-control", "no-cache");
            var dict = GeneratePayload(GenerateJWT());

            var postData = new FormUrlEncodedContent(dict);
            var request = new HttpRequestMessage(HttpMethod.Post, AuthSettings.TokenApplicationAccessUri);
            request.Content = postData;

            string headers = string.Empty;

            foreach(var x in request.Headers)
            {
                headers += "\n" + x.Key + " : " + x.Value;
            }

            var response = await client.SendAsync(request);
            var responseString = await response.Content.ReadAsStringAsync();


            var json = JsonConvert.DeserializeObject<TokenResponse>(responseString);

            return RedirectToPage("TokenRetrievedAppAccess", new
            {
                accessToken = json.access_token,
                expiresIn = json.expires_in,
                tokenType = json.token_type
            });
        }

    }
}

Pages/Callback.cshtml.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using CIS2Auth.Dto;
using CIS2Auth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace CIS2Auth.Pages
{
    public class CallbackModel : PageModel
    {

        private static HttpClient client = new HttpClient();

        [BindProperty]
        public CallbackViewModel CallbackData { get; set; }
        [BindProperty]
        public AuthSettingsViewModel AuthSettings { get; set; }

        [BindProperty]
        public string HelperText =>
            $"The authenticate page has called us back with the same state as we passed along with the authenticate code.  To complete the process we have to get a token.\nThis will POST to {AuthSettings.TokenCombinedUri} a json document";

        public void OnGet(string code,string state)
        {
            AuthSettings = new AuthSettingsViewModel();
            CallbackData = new CallbackViewModel
            {
                Code = code,
                State = state
            };
            
            //We now will go on and attempt to authenticate the user
        }

        public async Task<IActionResult> OnPost()
        {

            
            client.DefaultRequestHeaders.Add("cache-control", "no-cache");
            var dict = new Dictionary<string, string>()
            {
                {"grant_type", "authorization_code"},
                {"client_id", AuthSettings.CombinedApiKey},
                {"client_secret", AuthSettings.CombinedApiSecret},
                {"redirect_uri", AuthSettings.RedirectCombinedUri},
                {"code", CallbackData.Code}
            };
            var postData = new FormUrlEncodedContent(dict);
            var request = new HttpRequestMessage(HttpMethod.Post, AuthSettings.TokenCombinedUri);
            request.Content = postData;
            var response = await client.SendAsync(request);
            var responseString = await response.Content.ReadAsStringAsync();

            
            var json = JsonConvert.DeserializeObject<TokenResponse>(responseString);

            return RedirectToPage("TokenRetrieved", new
            {
                accessToken = json.access_token,
                expiresIn = json.expires_in,
                refreshToken = json.refresh_token,
                refreshTokenExpiresIn = json.refresh_token_expires_in,
                refreshCount = json.refresh_count,
                tokenType = json.token_type
            });
        }
    }


    

}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CIS2Auth.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using CIS2Auth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CIS2Auth.Pages
{
    public class IndexModel : PageModel
    {

        private readonly ILogger<IndexModel> _logger;
        Random random = new Random();
        private string chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }


        [BindProperty]
        public string HelperText => $"When authenticate is pressed we will redirect to {AuthSettings.AuthorizationCombinedUri}?clientid={AuthSettings.CombinedApiKey}&redirecturi={AuthSettings.RedirectCombinedUri}&response_type=code&state=random";


        [BindProperty]
        public AuthSettingsViewModel AuthSettings { get; set; }

        public void OnGet()
        {
            AuthSettings = new AuthSettingsViewModel();
        }

        public IActionResult OnPost()
        {
            var state = new string(Enumerable.Repeat(chars, 16).Select(s => s[random.Next(s.Length)]).ToArray());
            var dictionary = new Dictionary<string, string>()
            {
                {"client_id", AuthSettings.CombinedApiKey},
                {"redirect_uri", AuthSettings.RedirectCombinedUri },
                {"response_type", "code"},
                {"state", state}
            };
            var url = QueryHelpers.AddQueryString(AuthSettings.AuthorizationCombinedUri, dictionary);

            return Redirect(url);

            //This will do a redirection to https://sandbox.api.service.nhs.uk/oauth2/authorize?clientid=clientid&redirecturi=d&response_type=code&state=random

            //return RedirectToPage("Callback", new {code = "test", state = "state"});
        }

    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CIS2Auth.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Separate.cshtml.cs
using CIS2Auth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CIS2Auth.Pages
{
    public class SeparateModel : PageModel
    {


        private readonly ILogger<SeparateModel> _logger;
        Random random = new Random();
        private string chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

        public SeparateModel(ILogger<SeparateModel> logger)
        {
            _logger = logger;
        }

        [BindProperty]
        public string HelperText => $"When authenticate is pressed we will redirect to {AuthSettings.AuthorizationSeparateUri}?client_id={AuthSettings.SeparateApiKey}&redirect_uri={AuthSettings.RedirectSeparateUri}&response_type=code&state=random";


        [BindProperty]
        public AuthSettingsViewModel AuthSettings { get; set; }

        public void OnGet()
        {
            AuthSettings = new AuthSettingsViewModel();
        }

        public IActionResult OnPost()
        {
            var state = new string(Enumerable.Repeat(chars, 16).Select(s => s[random.Next(s.Length)]).ToArray());
            var dictionary = new Dictionary<string, string>()
            {
                {"client_id", AuthSettings.SeparateApiKey},
                {"redirect_uri", AuthSettings.RedirectSeparateUri },
                {"response_type", "code"},
                {"state", state}
            };
            var url = QueryHelpers.AddQueryString(AuthSettings.AuthorizationSeparateUri, dictionary);

            return Redirect(url);
        }

    }
}

Pages/TokenRetrieved.cshtml.cs
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using CIS2Auth.Dto;
using CIS2Auth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace CIS2Auth.Pages
{
    public class TokenRetrievedModel : PageModel
    {

        private static HttpClient client = new HttpClient();

        [BindProperty]
        public TokenResponse Token { get; set; }


        [BindProperty]
        public string GetUserResponse { get; set; }

        public void OnGet(string accessToken, long expiresIn,string refreshToken,long refreshTokenExpiresIn,int refreshCount ,string tokenType, string getUserResponse)
        {
            Token = new TokenResponse
            {
                access_token = accessToken,
                expires_in = expiresIn,
                refresh_token = refreshToken,
                refresh_token_expires_in = refreshTokenExpiresIn,
                refresh_count = refreshCount,
                token_type = tokenType
            };
            GetUserResponse = getUserResponse;
        }

        public async Task<IActionResult> OnPostGetUserInfo()
        {
            var authSettings = new AuthSettingsViewModel();
            client.DefaultRequestHeaders.Add("cache-control", "no-cache");
            
            var request = new HttpRequestMessage(HttpMethod.Get, authSettings.UserInfoCombinedUri);

            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", Token.access_token);

            var response = await client.SendAsync(request);
            var responseString = await response.Content.ReadAsStringAsync();

            GetUserResponse = responseString;


            /*
             *{
    "nhsid_useruid": "910000000001",
    "name": "USERQ RANDOM Mr",
    "nhsid_nrbac_roles": [
        {
            "activities": [
                "Perform Prescription Preparation",
                "View Patient Medication",
                "Amend Patient Demographics",
                "Nurse Prescribers Formulary (NPF) Prescribing"
            ],
            "activity_codes": [
                "B0278",
                "B0401",
                "B0825",
                "B0058"
            ],
            "org_code": "RBA",
            "person_orgid": "555254239107",
            "person_roleid": "555254240100",
            "role_code": "S8000:G8000:R8001",
            "role_name": "\"Clinical\":\"Clinical Provision\":\"Nurse Access Role\""
        },
        {
            "activities": [
                "Manage Workgroups",
                "Independent Prescribing",
                "Execute CDS Extracts (NHS Group Pseud. Data)",
                "Manage Workgroup Membership"
            ],
            "activity_codes": [
                "B0100",
                "B0420",
                "B1510",
                "B0090"
            ],
            "org_code": "RBA",
            "person_orgid": "555254239107",
            "person_roleid": "555254242102",
            "role_code": "S8000:G8000:R8000",
            "role_name": "\"Clinical\":\"Clinical Provision\":\"Clinical Practitioner Access Role\""
        },
        {
            "activities": [
                "Perform Pharmacy Activities",
                "Verify Prescription",
                "Manage Pharmacy Activities",
                "View Patient Medication"
            ],
            "activity_codes": [
                "B0570",
                "B0068",
                "B0572",
                "B0401"
            ],
            "org_code": "RBA",
            "person_orgid": "555254239107",
            "person_roleid": "555254241101",
            "role_code": "S8000:G8000:R8003",
            "role_name": "\"Clinical\":\"Clinical Provision\":\"Health Professional Access Role\""
        },
        {
            "activities": [
                "Perform Pharmacy Activities",
                "Verify Prescription",
                "Manage Pharmacy Activities",
                "View Patient Medication"
            ],
            "activity_codes": [
                "B0570",
                "B0068",
                "B0572",
                "B0401"
            ],
            "org_code": "RBA",
            "person_orgid": "555254239107",
            "person_roleid": "093895563513",
            "role_code": "S8000:G8000:R8003",
            "role_name": "\"Clinical\":\"Clinical Provision\":\"Health Professional Access Role\""
        }
    ],
    "sub": "910000000001"
}
             *
             *
             */
            ModelState.Remove(nameof(GetUserResponse));
            return Page();
        }

        public async Task<IActionResult> OnPostRefreshToken()
        {
            //We now need to get the user info

            //We use the same token uri but different parameters
            var authSettings = new AuthSettingsViewModel();
            client.DefaultRequestHeaders.Add("cache-control", "no-cache");
            var dict = new Dictionary<string, string>()
            {
                {"grant_type", "refresh_token"},
                {"client_id", authSettings.CombinedApiKey},
                {"client_secret", authSettings.CombinedApiSecret},
                {"refresh_token", Token.refresh_token}
            };
            var postData = new FormUrlEncodedContent(dict);
            var request = new HttpRequestMessage(HttpMethod.Post, authSettings.TokenCombinedUri);
            request.Content = postData;
            var response = await client.SendAsync(request);
            var responseString = await response.Content.ReadAsStringAsync();


            var json = JsonConvert.DeserializeObject<TokenResponse>(responseString);

            return RedirectToPage("TokenRetrieved", new
            {
                accessToken = json.access_token,
                expiresIn = json.expires_in,
                refreshToken = json.refresh_token,
                refreshTokenExpiresIn = json.refresh_token_expires_in,
                refreshCount = json.refresh_count,
                tokenType = json.token_type
            });
        }
    }
}

Pages/TokenRetrievedAppAccess.cshtml.cs
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using CIS2Auth.Dto;
using CIS2Auth.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace CIS2Auth.Pages
{
    public class TokenRetrievedAppAccessModel : PageModel
    {

        [BindProperty]
        public TokenResponse Token { get; set; }


        [BindProperty]
        public string GetUserResponse { get; set; }

        public void OnGet(string accessToken, long expiresIn,string tokenType, string getUserResponse)
        {
            Token = new TokenResponse
            {
                access_token = accessToken,
                expires_in = expiresIn,
                token_type = tokenType
            };
            GetUserResponse = getUserResponse;
        }

        
    }
}

Pages/ApplicationAccess.cshtml
@page
@model CIS2Auth.Pages.ApplicationAccessModel
@{
	ViewData["Title"] = "Application Access Model";
}

<br />
<h2 class="text-info">CIS2 Authorisation - Application Access</h2>
<br />
<h4 class="text-info">@Model.HelperText</h4>
<div class="border container" style="padding: 30px;">
	<form method="post">
		<div class="text-danger" asp-validation-summary="ModelOnly"></div>
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="AuthSettings.AppAccessApiKey"></label>
			</div>
			<div class="col-9">
				<input asp-for="AuthSettings.AppAccessApiKey" class="form-control" />
			</div>
			<span asp-validation-for="AuthSettings.AppAccessApiKey" class="text-danger"></span>
		</div>
		
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="JWT"><p>JWT (Check out <a href="https://jwt.io/" target="_blank">jwt.io</a>)</p></label>
			</div>
			<div class="col-9">
				<input asp-for="JWT" class="form-control"/>
			</div>
			<span asp-validation-for="JWT" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="PrivateKey"></label>
			</div>
			<div class="col-9">
				<input asp-for="PrivateKey" class="form-control"/>
			</div>
			<span asp-validation-for="PrivateKey" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="PublicKey"></label>
			</div>
			<div class="col-9">
				<input asp-for="PublicKey" class="form-control"/>
			</div>
			<span asp-validation-for="PublicKey" class="text-danger"></span>
		</div>
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="GetTokenPayload"></label>
			</div>
			<div class="col-9">
				<textarea asp-for="GetTokenPayload" rows="5" class="form-control"></textarea>
			</div>
			<span asp-validation-for="Kid" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="AuthSettings.TokenApplicationAccessUri"></label>
			</div>
			<div class="col-9">
				<input asp-for="AuthSettings.TokenApplicationAccessUri" class="form-control" />
			</div>
			<span asp-validation-for="AuthSettings.TokenApplicationAccessUri" class="text-danger"></span>
		</div>
		

		<div class="form-group row">
			<div class="col-3 offset-3">
				<button type="submit" class="btn btn-primary form-control">Get Token</button>
			</div>
		</div>
	</form>
</div>

@section Scripts
{
	<partial name="_ValidationScriptsPartial" />
	<script type="text/javascript">
	$(function () {
		$('#MonitorDefinition_Method').change(function () {
			var value = $(this).val();
			if (value == 1) {
				$('#RequestBody').show();
			} else {
				$('#RequestBody').hide();
			}
		});
	});</script>
}

Pages/Callback.cshtml
@page
@model CIS2Auth.Pages.CallbackModel
@{
	ViewData["Title"] = "Combined Callback page";
}

<br />
<h2 class="text-info">CIS2 Combined Callback</h2>
<br />
<h4 class="text-info">
	<span style="white-space: pre-line">@Model.HelperText</span>
</h4>

<div class="border container" style="padding: 30px;">
	<form method="post">
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="AuthSettings.CombinedApiKey"></label>
			</div>
			<div class="col-9">
				<input asp-for="AuthSettings.CombinedApiKey" class="form-control"/>
			</div>
			<span asp-validation-for="AuthSettings.CombinedApiKey" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="AuthSettings.CombinedApiSecret"></label>
			</div>
			<div class="col-9">
				<input asp-for="AuthSettings.CombinedApiSecret" class="form-control"/>
			</div>
			<span asp-validation-for="AuthSettings.CombinedApiSecret" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="AuthSettings.AuthorizationSeparateUri"></label>
			</div>
			<div class="col-9">
				<input asp-for="AuthSettings.AuthorizationSeparateUri" class="form-control"/>
			</div>
			<span asp-validation-for="AuthSettings.AuthorizationSeparateUri" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="AuthSettings.TokenCombinedUri"></label>
			</div>
			<div class="col-9">
				<input asp-for="AuthSettings.TokenCombinedUri" class="form-control"/>
			</div>
			<span asp-validation-for="AuthSettings.TokenCombinedUri" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="CallbackData.Code"></label>
			</div>
			<div class="col-9">
				<input asp-for="CallbackData.Code" class="form-control"/>
			</div>
			<span asp-validation-for="CallbackData.Code" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3">
				<label asp-for="CallbackData.State"></label>
			</div>
			<div class="col-9">
				<input asp-for="CallbackData.State" class="form-control"/>
			</div>
			<span asp-validation-for="CallbackData.State" class="text-danger"></span>
		</div>

		<div class="form-group row">
			<div class="col-3 offset-3">
				<button type="submit" class="btn btn-primary form-control">Get Token</button>
			</div>
		</div>
	</form>
</div>

Pages/TokenRetrieved.cshtml
@page
@model CIS2Auth.Pages.TokenRetrievedModel
@{
	ViewData["Title"] = "Token Retrieved";
}
<br />
<h2 class="text-info">CIS2 Token Retrieved</h2>
<br />

<div class="border container" style="padding: 30px;">
	<form method="post">
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.access_token"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.access_token" class="form-control" value="@Model.Token.access_token"/>
			</div>
		</div>
		
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.refresh_token"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.refresh_token" class="form-control" value="@Model.Token.refresh_token" />
			</div>
		</div>
			
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.expires_in"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.expires_in" class="form-control" value="@Model.Token.expires_in"/>
			</div>
		</div>
		
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.refresh_token_expires_in"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.refresh_token_expires_in" class="form-control" value="@Model.Token.refresh_token_expires_in"/>
			</div>
		</div>
		
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.refresh_count"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.refresh_count" class="form-control" value="@Model.Token.refresh_count"/>
			</div>
		</div>
		
		
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.token_type"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.token_type" class="form-control" value="@Model.Token.token_type"/>
			</div>
		</div>
		
		
		<div class="form-group row">
			<div class="col-3">
				<label>Get User Info Response</label>
			</div>
			<div class="col-9">
				<textarea asp-for="GetUserResponse" rows="5" class="form-control" value="@Model.GetUserResponse"></textarea>
			</div>
		</div>

		
		<div class="form-group row">
			<div class="col-3 offset-3">
				<button type="submit" asp-page-handler="GetUserInfo" class="btn btn-primary form-control">Get User Info</button>
			</div>
			<div class="col-3 offset-3">
				<button type="submit" asp-page-handler="RefreshToken" class="btn btn-primary form-control">Refresh Token</button>
			</div>
		</div>
	</form>
</div>

Pages/TokenRetrievedAppAccess.cshtml
@page
@model CIS2Auth.Pages.TokenRetrievedAppAccessModel
@{
	ViewData["Title"] = "Token Retrieved Application Access";
}
<br />
<h2 class="text-info">CIS2 Token Retrieved Application Access</h2>
<br />

<div class="border container" style="padding: 30px;">
	<div class="form-group row">
		<div class="col-3">
			<label asp-for="Token.access_token"></label>
		</div>
		<div class="col-9">
			<input asp-for="Token.access_token" class="form-control" value="@Model.Token.access_token"/>
		</div>
	</div>
		
	<div class="form-group row">
		<div class="col-3">
			<label asp-for="Token.expires_in"></label>
		</div>
		<div class="col-9">
			<input asp-for="Token.expires_in" class="form-control" value="@Model.Token.expires_in"/>
		</div>
	</div>
		
	<div class="form-group row">
		<div class="col-3">
			<label asp-for="Token.token_type"></label>
		</div>
		<div class="col-9">
			<input asp-for="Token.token_type" class="form-control" value="@Model.Token.token_type"/>
		</div>
	</div>
</div>

Pages/TokenRetrievedSeparate.cshtml
@page
@model CIS2Auth.Pages.TokenRetrievedSeparateModel
@{
	ViewData["Title"] = "Token Retrieved Separate";
}
<br />
<h2 class="text-info">CIS2 Token Retrieved Separate</h2>
<br />

<div class="border container" style="padding: 30px;">
	<form method="post">
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.access_token"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.access_token" class="form-control" value="@Model.Token.access_token"/>
			</div>
		</div>
		
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.expires_in"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.expires_in" class="form-control" value="@Model.Token.expires_in"/>
			</div>
		</div>
		
		<div class="form-group row">
			<div class="col-3">
				<label asp-for="Token.token_type"></label>
			</div>
			<div class="col-9">
				<input asp-for="Token.token_type" class="form-control" value="@Model.Token.token_type"/>
			</div>
		</div>
		<div class="form-group row">
			<div class="col-3">
				<label>Get User Info Response</label>
			</div>
			<div class="col-9">
				<textarea asp-for="GetUserResponse" rows="5" class="form-control" value="@Model.GetUserResponse"></textarea>
			</div>
		</div>
		<div class="form-group row">
			<div class="col-3 offset-3">
				<button type="submit" asp-page-handler="GetUserInfo" class="btn btn-primary form-control">Get User Info</button>
			</div>
		</div>
	</form>
</div>